webapp/blog/models.py
from .. import db
from sqlalchemy.inspection import inspect


class Serializer(object):

    @staticmethod
    def serialize(self):
        return {c: getattr(self, c) for c in inspect(self).attrs.keys()}

    @staticmethod
    def serialize_list(l):
        return [m.serialize() for m in l]


class Post(db.Model, Serializer):
    id = db.Column(db.Integer(), primary_key=True)
    olx_id = db.Column(db.Integer())
    title = db.Column(db.String(255))
    price = db.Column(db.Integer())
    photo = db.Column(db.String(255))
    seller = db.Column(db.String(255))

    def __init__(self, title=""):
        self.title = title

    def __repr__(self):
        return "<Post '{}'>".format(self.title)

    # TODO use Marshmellow
    def serialize(self, role):
        d = Serializer.serialize(self)
        if role == 'default' or role == 'poster':
            del d['seller']
        return d

webapp/blog/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length


class CommentForm(Form):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])

class PostForm(Form):
    title = StringField('Title', [
        DataRequired(),
        Length(max=255)
    ])
    text = TextAreaField('Content', [DataRequired()])

main.py
import os
from webapp import create_app

env = os.environ.get('WEBAPP_ENV', 'dev')
app = create_app('config.%sConfig' % env.capitalize())


if __name__ == '__main__':
    app.run()

webapp/__init__.py
from flask import Flask

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. project.config.ProdConfig
    """
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    migrate.init_app(app, db)

    from .auth import create_module as auth_create_module
    from .blog import create_module as blog_create_module
    from .main import create_module as main_create_module
    auth_create_module(app)
    blog_create_module(app)
    main_create_module(app)

    return app

webapp/blog/__init__.py
def create_module(app, **kwargs):
    from .controllers import blog_blueprint
    app.register_blueprint(blog_blueprint)

webapp/blog/controllers.py
from flask import render_template, Blueprint, jsonify
from flask_login import login_required, current_user
from .models import db, Post

import parser

blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/olx"
)


@blog_blueprint.route('/')
@login_required
def home():
    return render_template(
        'home.html',
    )


limits = {
    'default': 100,
    'poster': 200,
    'admin': 300
}


@blog_blueprint.route('/refresh')
@login_required
def refresh():
    role = current_user.roles[-1].name
    limit = limits[role]

    data = parser.main(limit)
    Post.query.delete()

    ids = []

    post_data = []
    for item in data:
        if item['id'] in ids:
            continue

        param = item['params'][0]['value'] if item['params'] else None
        photo = item['photos'][0]['link'] if item['photos'] else None

        post = Post()
        post.olx_id = item['id']
        post.title = item['title']
        post.price = param['value']
        post.photo = photo
        post.seller = item['user']['name']

        ids.append(item['id'])
        post_data.append(post)

    db.session.bulk_save_objects(post_data)
    db.session.commit()

    serializer = [p.serialize(role) for p in Post.query.limit(limit).all()]

    return jsonify(posts=serializer)


@blog_blueprint.route('/delete/<int:id>', methods=['DELETE'])
@login_required
def delete_post(id):
    post = Post.query.filter_by(olx_id=id).first()
    db.session.delete(post)
    db.session.commit()
    return '', 201


@blog_blueprint.route('/sort/<order>', methods=['GET'])
@login_required
def sort_posts(order=None):
    role = role = current_user.roles[-1].name
    limit = limits[role]

    if order == 'asc':
        serializer = [p.serialize(role) for p in Post.query.order_by(Post.price).limit(limit).all()]
    elif order == 'desc':
        serializer = [p.serialize(role) for p in Post.query.order_by(Post.price.desc()).limit(limit).all()]
    else:
        serializer = [p.serialize(role) for p in Post.query.limit(limit).all()]

    return jsonify(posts=serializer)

webapp/main/__init__.py
def create_module(app, **kwargs):
    from .controllers import main_blueprint
    app.register_blueprint(main_blueprint)

webapp/main/controllers.py
from flask import Blueprint, redirect, url_for, render_template

main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route('/')
def index():
    return redirect(url_for('blog.home'))

webapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.13/vue.js"></script>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    <div class="row row-lg-4">
        <div class="col">
            {% block head %}
            {% include 'head.html' %}
            {% endblock %}
        </div>
    </div>
    {% include 'messages.html' %}
    {% block body %}
    <div class="row">
        <div class="col-lg-9">
            {% block leftbody %}
            {% endblock %}
        </div>
        <div class="col-lg-3 rounded">
            {% block rightbody %}
            {% include 'rightbody.html' %}
            {% endblock %}
        </div>
    </div>
    {% endblock %}
    {% include 'footer.html' %}
</div>
</body>
{% block js %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>    </body>
</html>

webapp/templates/blog/edit.html
{% extends "base.html" %}
{% block title %}Post Creation{% endblock %}
{% block body %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>Edit Post</h1>
        </div>
    </div>

<div class="row">
    <form method="POST" action="{{ url_for('.edit_post', id=post.id) }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
            {% for e in form.title.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.title(class_='form-control') }}
        </div>
        <div class="form-group">
            {{ form.text.label }}
            {% if form.text.errors %}
            {% for e in form.text.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.text(id="editor", class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
</div>
    {% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

webapp/templates/blog/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}
<div id="app">
  <div v-if="data">
    <div>
      <a @click="sort_posts" style="cursor: pointer"
        >Сортировать по цене <span v-if="order==='asc'">&darr;</span
        ><span v-else-if="order==='desc'">&uarr;</span></a
      >
    </div>
    <div class="row">
      <div class="col-md-3 col-sm-6" v-for="item in items" :key="item.id">
        <div class="card">
          <img class="card-img-top" :src="item.photo" alt="Card image cap" />
          <div class="card-body">
            <h5 class="card-title">[[item.title]]</h5>
            <p class="card-text">[[item.price]] UAH</p>
            <p v-if="item.seller" class="card-text">
              Продавец: [[item.seller]]
            </p>
            <button
              href="#"
              @click="delete_post(item.olx_id)"
              class="btn btn-danger"
            >
              Удалить
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div v-else>
    <button class="btn btn-primary" @click="refresh">Обновить</button>
  </div>
  <script>
    new Vue({
      el: "#app",
      delimiters: ["[[", "]]"],
      data: {
        data: null,
        order: null,
      },
      computed: {
        items() {
          return this.data
            .map((item) => {
              if (item.photo) {
                item.photo = item.photo
                  .replace("{width}", "640")
                  .replace("{height}", "480");
              }

              return item;
            })
            .slice(5);
        },
      },
      methods: {
        refresh() {
          fetch("{{ url_for('blog.refresh') }}")
            .then((response) => response.json())
            .then((data) => {
              this.data = data.posts;
            });
        },
        delete_post(id) {
          let url = "{{ url_for('blog.delete_post', id=999) }}";
          url = url.replace("999", id);
          fetch(url, { method: "DELETE" });
          this.data = this.data.filter((item) => item.olx_id !== id);
        },
        sort_posts() {
          let url = "{{ url_for('blog.sort_posts', order='xxx') }}";

          switch (this.order) {
            case "desc":
              this.order = "asc";
              break;
            case "asc":
              this.order = "desc";
              break;
            default:
              this.order = "asc";
          }

          url = url.replace("xxx", this.order);

          fetch(url)
            .then((response) => response.json())
            .then((data) => {
              this.data = data.posts;
            });
        },
      },
    });
  </script>
  {% endblock %}
</div>

webapp/templates/blog/new.html
{% extends "base.html" %}
{% block title %}Post Creation{% endblock %}
{% block body %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>Create a New Post</h1>
        </div>
    </div>

<div class="row">
    <form method="POST" action="{{ url_for('.new_post') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label }}
            {% if form.title.errors %}
            {% for e in form.title.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.title(class_='form-control') }}
        </div>
        <div class="form-group">
            {{ form.text.label }}
            {% if form.text.errors %}
            {% for e in form.text.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.text(id="editor", class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
</div>
    {% endblock %}

{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

webapp/templates/blog/post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block leftbody %}
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h1>{{ post.title }}</h1>
        </div>
    </div>
    <div class="row shadow-sm">
        <div class="col-lg-6">
            <p>Written By <a href="{{ url_for('blog.posts_by_user', username=post.user.username) }}">{{ post.user.username }}</a> on {{ post.publish_date }}</p>
        </div>
        <div class="col-lg-6">
            <p class="text-right"> Tags: {% for tag in tags %}
                <a href="{{ url_for('blog.posts_by_tag', tag_name=tag.title) }}">{{tag.title}}</a>
                {% endfor %}
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ post.text | safe }}
        </div>
    </div>
    {% if current_user.id == post.user_id %}
    <div class="col-lg-2">
        <a href="{{ url_for('.edit_post', id=post.id) }}" class="btn
       btn-primary">Edit</a>
    </div>
    {% endif %}
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>New Comment:</h4>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.name.label }}
                    {% if form.name.errors %}
                    {% for e in form.name.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.name(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                    {% for e in form.text.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                    {% endif %}
                    {{ form.text(class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="Add Comment">
            </form>
        </div>
    </div>
</div>
<div class="p-4 shadow-sm">
    <div class="row">
        <div class="col">
            <h4>Comments ({{ comments | length }})</h4>
        </div>
    </div>
    <div class="row p-2">
        <div class="col">
            {% if comments | length == 0 %}
            <p>There are no comments for this post.</p>
            {% else %}
            {% for comment in comments %}
            <div class="shadow-sm p-2">
                <dt>By: {{ comment.name }} on {{ comment.date }}</dt>
                <dd>{{ comment.text }}</dd>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/blog/rightbody.html
<div class="row">
    <div class="col">
        <h5>Recent Posts</h5>
    </div>
</div>
<ul class="list-group">
    {% for post in recent %}
    <li class="list-group-item">
        <a href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>
<div class="row">
    <div class="col">
        <h5>Popular Tags</h5>
    </div>
</div>
<ul class="list-group">
    {% for tag in top_tags %}
    <li class="list-group-item"
    ><a href="{{ url_for('blog.posts_by_tag', tag_name=tag[0].title) }}">{{ tag[0].title }}</a>
    </li>
    {% endfor %}
</ul>

webapp/templates/blog/tag.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ tag.title }}{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts With Tag {{ tag.title }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}

{% endblock %}

webapp/templates/blog/user.html
{% extends "base.html" %}
{% import 'macros.html' as macros %}

{% block title %}{{ user.username }}'s Posts{% endblock %}
{% block leftbody %}
<div class="row">
    <div class="col bg-light">
        <h1 class="text-center">Posts By {{ user.username }}</h1>
    </div>
</div>
{{ macros.render_posts(posts, pagination=False) }}

{% endblock %}

webapp/templates/footer.html
<div class="row"></div>

webapp/templates/head.html
<div class="container bg-info rounded"></div>

webapp/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if pagination.has_prev %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.prev().page) }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
        </li>
        {% endif %}
        {% for page in pagination.iter_pages() %}
        {% if page %}
        {% if page != pagination.page %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
        </li>
        {% else %}
        <li class="page-item active">
            <a class="page-link" href="">{{ page }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="page-item">
            <a class="page-link">…</a>
        <li>
            {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('blog.home', page=pagination.next().page) }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}

{% macro render_posts(posts, pagination=True) %}
{% if pagination %}
{% set _posts = posts.items %}
{% else %}
{% set _posts = posts %}
{% endif %}

{% for post in _posts %}
<div >
    <h1>
        <a class="text-dark" href="{{ url_for('blog.post', post_id=post.id) }}">{{ post.title }}</a>
    </h1>
</div>
<div class="row">
    <div class="col">
        {{ post.text | truncate(500) | safe }}
        <a href="{{ url_for('blog.post', post_id=post.id) }}">Read More</a>
    </div>
</div>
{% endfor %}
{% endmacro %}

webapp/templates/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

webapp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('blog.home')}}"
          >Home <span class="sr-only">(current)</span></a
        >
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('blog.home')}}"></a>
      </li>
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="#user">
          <i class="fa fa-fw fa-sign-out"></i>{{ current_user }}</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.logout')}}">
          <i class="fa fa-fw fa-sign-out"></i>Logout</a
        >
      </li>

      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.login')}}">
          <i class="fa fa-fw fa-sign-in"></i>Login</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.register')}}">
          <i class="fa fa-fw fa-sign-in"></i>Register</a
        >
      </li>
      {% endif %}
    </ul>
  </div>
</nav>